import type {
  Account,
  Budget,
  Category,
  ClassificationFeedback,
  ImportRecord,
  Merchant,
  Project,
  Tag,
  Transaction,
  UserRule,
} from '../../domain/entities';
import type { EntityDefinition } from './BaseRepository';
import {
  booleanValue,
  optionalNumber,
  optionalString,
  optionalValue,
  requiredBoolean,
  requiredNumber,
  requiredString,
  stringArray,
} from './mappingHelpers';

export const transactionDefinition: EntityDefinition<Transaction> = {
  tableName: 'transactions',
  columns: [
    'id',
    'type',
    'amount_minor',
    'currency',
    'occurred_at',
    'category_id',
    'subcategory_id',
    'account_id',
    'target_account_id',
    'merchant_id',
    'merchant_raw_name',
    'project_id',
    'note',
    'source',
    'source_reference_id',
    'original_text',
    'confidence',
    'confirmation_status',
    'duplicate_status',
    'related_transaction_id',
    'fingerprint',
    'created_at',
    'updated_at',
    'deleted_at',
    'sync_status',
  ],
  defaultOrderBy: 'occurred_at DESC, created_at DESC',
  toValues: transaction => ({
    id: transaction.id,
    type: transaction.type,
    amount_minor: transaction.amountMinor,
    currency: transaction.currency,
    occurred_at: transaction.occurredAt,
    category_id: optionalValue(transaction.categoryId),
    subcategory_id: optionalValue(transaction.subcategoryId),
    account_id: optionalValue(transaction.accountId),
    target_account_id: optionalValue(transaction.targetAccountId),
    merchant_id: optionalValue(transaction.merchantId),
    merchant_raw_name: optionalValue(transaction.merchantRawName),
    project_id: optionalValue(transaction.projectId),
    note: optionalValue(transaction.note),
    source: transaction.source,
    source_reference_id: optionalValue(transaction.sourceReferenceId),
    original_text: optionalValue(transaction.originalText),
    confidence: optionalValue(transaction.confidence),
    confirmation_status: transaction.confirmationStatus,
    duplicate_status: transaction.duplicateStatus,
    related_transaction_id: optionalValue(transaction.relatedTransactionId),
    fingerprint: optionalValue(transaction.fingerprint),
    created_at: transaction.createdAt,
    updated_at: transaction.updatedAt,
    deleted_at: optionalValue(transaction.deletedAt),
    sync_status: transaction.syncStatus,
  }),
  fromRow: row => ({
    id: requiredString(row, 'id'),
    type: requiredString(row, 'type') as Transaction['type'],
    amountMinor: requiredNumber(row, 'amount_minor'),
    currency: requiredString(row, 'currency'),
    occurredAt: requiredString(row, 'occurred_at'),
    categoryId: optionalString(row, 'category_id'),
    subcategoryId: optionalString(row, 'subcategory_id'),
    accountId: optionalString(row, 'account_id'),
    targetAccountId: optionalString(row, 'target_account_id'),
    merchantId: optionalString(row, 'merchant_id'),
    merchantRawName: optionalString(row, 'merchant_raw_name'),
    projectId: optionalString(row, 'project_id'),
    note: optionalString(row, 'note'),
    source: requiredString(row, 'source') as Transaction['source'],
    sourceReferenceId: optionalString(row, 'source_reference_id'),
    originalText: optionalString(row, 'original_text'),
    confidence: optionalNumber(row, 'confidence'),
    confirmationStatus: requiredString(
      row,
      'confirmation_status',
    ) as Transaction['confirmationStatus'],
    duplicateStatus: requiredString(
      row,
      'duplicate_status',
    ) as Transaction['duplicateStatus'],
    relatedTransactionId: optionalString(row, 'related_transaction_id'),
    fingerprint: optionalString(row, 'fingerprint'),
    createdAt: requiredString(row, 'created_at'),
    updatedAt: requiredString(row, 'updated_at'),
    deletedAt: optionalString(row, 'deleted_at'),
    syncStatus: requiredString(row, 'sync_status') as Transaction['syncStatus'],
  }),
};

export const categoryDefinition: EntityDefinition<Category> = {
  tableName: 'categories',
  columns: [
    'id',
    'type',
    'parent_id',
    'system_key',
    'name',
    'icon',
    'sort_order',
    'is_system',
    'is_hidden',
    'created_at',
    'updated_at',
  ],
  defaultOrderBy: 'sort_order ASC, name ASC',
  toValues: category => ({
    id: category.id,
    type: category.type,
    parent_id: optionalValue(category.parentId),
    system_key: optionalValue(category.systemKey),
    name: category.name,
    icon: optionalValue(category.icon),
    sort_order: category.sortOrder,
    is_system: booleanValue(category.isSystem),
    is_hidden: booleanValue(category.isHidden),
    created_at: category.createdAt,
    updated_at: category.updatedAt,
  }),
  fromRow: row => ({
    id: requiredString(row, 'id'),
    type: requiredString(row, 'type') as Category['type'],
    parentId: optionalString(row, 'parent_id'),
    systemKey: optionalString(row, 'system_key'),
    name: requiredString(row, 'name'),
    icon: optionalString(row, 'icon'),
    sortOrder: requiredNumber(row, 'sort_order'),
    isSystem: requiredBoolean(row, 'is_system'),
    isHidden: requiredBoolean(row, 'is_hidden'),
    createdAt: requiredString(row, 'created_at'),
    updatedAt: requiredString(row, 'updated_at'),
  }),
};

export const accountDefinition: EntityDefinition<Account> = {
  tableName: 'accounts',
  columns: [
    'id',
    'name',
    'type',
    'currency',
    'include_in_net_worth',
    'opening_balance_minor',
    'current_balance_minor',
    'icon',
    'sort_order',
    'is_hidden',
    'created_at',
    'updated_at',
  ],
  defaultOrderBy: 'sort_order ASC, name ASC',
  toValues: account => ({
    id: account.id,
    name: account.name,
    type: account.type,
    currency: account.currency,
    include_in_net_worth: booleanValue(account.includeInNetWorth),
    opening_balance_minor: optionalValue(account.openingBalanceMinor),
    current_balance_minor: optionalValue(account.currentBalanceMinor),
    icon: optionalValue(account.icon),
    sort_order: account.sortOrder,
    is_hidden: booleanValue(account.isHidden),
    created_at: account.createdAt,
    updated_at: account.updatedAt,
  }),
  fromRow: row => ({
    id: requiredString(row, 'id'),
    name: requiredString(row, 'name'),
    type: requiredString(row, 'type') as Account['type'],
    currency: requiredString(row, 'currency'),
    includeInNetWorth: requiredBoolean(row, 'include_in_net_worth'),
    openingBalanceMinor: optionalNumber(row, 'opening_balance_minor'),
    currentBalanceMinor: optionalNumber(row, 'current_balance_minor'),
    icon: optionalString(row, 'icon'),
    sortOrder: requiredNumber(row, 'sort_order'),
    isHidden: requiredBoolean(row, 'is_hidden'),
    createdAt: requiredString(row, 'created_at'),
    updatedAt: requiredString(row, 'updated_at'),
  }),
};

export const projectDefinition: EntityDefinition<Project> = {
  tableName: 'projects',
  columns: [
    'id',
    'name',
    'description',
    'start_date',
    'end_date',
    'budget_minor',
    'currency',
    'is_archived',
    'created_at',
    'updated_at',
  ],
  defaultOrderBy: 'created_at DESC',
  toValues: project => ({
    id: project.id,
    name: project.name,
    description: optionalValue(project.description),
    start_date: optionalValue(project.startDate),
    end_date: optionalValue(project.endDate),
    budget_minor: optionalValue(project.budgetMinor),
    currency: project.currency,
    is_archived: booleanValue(project.isArchived),
    created_at: project.createdAt,
    updated_at: project.updatedAt,
  }),
  fromRow: row => ({
    id: requiredString(row, 'id'),
    name: requiredString(row, 'name'),
    description: optionalString(row, 'description'),
    startDate: optionalString(row, 'start_date'),
    endDate: optionalString(row, 'end_date'),
    budgetMinor: optionalNumber(row, 'budget_minor'),
    currency: requiredString(row, 'currency'),
    isArchived: requiredBoolean(row, 'is_archived'),
    createdAt: requiredString(row, 'created_at'),
    updatedAt: requiredString(row, 'updated_at'),
  }),
};

export const tagDefinition: EntityDefinition<Tag> = {
  tableName: 'tags',
  columns: ['id', 'name', 'created_at', 'updated_at'],
  defaultOrderBy: 'name ASC',
  toValues: tag => ({
    id: tag.id,
    name: tag.name,
    created_at: tag.createdAt,
    updated_at: tag.updatedAt,
  }),
  fromRow: row => ({
    id: requiredString(row, 'id'),
    name: requiredString(row, 'name'),
    createdAt: requiredString(row, 'created_at'),
    updatedAt: requiredString(row, 'updated_at'),
  }),
};

export const merchantDefinition: EntityDefinition<Merchant> = {
  tableName: 'merchants',
  columns: [
    'id',
    'canonical_name',
    'normalized_name',
    'aliases_json',
    'default_category_id',
    'default_subcategory_id',
    'created_at',
    'updated_at',
  ],
  defaultOrderBy: 'canonical_name ASC',
  toValues: merchant => ({
    id: merchant.id,
    canonical_name: merchant.canonicalName,
    normalized_name: merchant.normalizedName,
    aliases_json: JSON.stringify(merchant.aliases),
    default_category_id: optionalValue(merchant.defaultCategoryId),
    default_subcategory_id: optionalValue(merchant.defaultSubcategoryId),
    created_at: merchant.createdAt,
    updated_at: merchant.updatedAt,
  }),
  fromRow: row => ({
    id: requiredString(row, 'id'),
    canonicalName: requiredString(row, 'canonical_name'),
    normalizedName: requiredString(row, 'normalized_name'),
    aliases: stringArray(row, 'aliases_json'),
    defaultCategoryId: optionalString(row, 'default_category_id'),
    defaultSubcategoryId: optionalString(row, 'default_subcategory_id'),
    createdAt: requiredString(row, 'created_at'),
    updatedAt: requiredString(row, 'updated_at'),
  }),
};

export const userRuleDefinition: EntityDefinition<UserRule> = {
  tableName: 'user_rules',
  columns: [
    'id',
    'rule_type',
    'origin',
    'pattern',
    'transaction_type',
    'category_id',
    'subcategory_id',
    'account_id',
    'priority',
    'enabled',
    'usage_count',
    'last_used_at',
    'created_at',
    'updated_at',
  ],
  defaultOrderBy: 'priority DESC, created_at ASC',
  toValues: rule => ({
    id: rule.id,
    rule_type: rule.ruleType,
    origin: rule.origin ?? 'USER_CREATED',
    pattern: rule.pattern,
    transaction_type: optionalValue(rule.transactionType),
    category_id: optionalValue(rule.categoryId),
    subcategory_id: optionalValue(rule.subcategoryId),
    account_id: optionalValue(rule.accountId),
    priority: rule.priority,
    enabled: booleanValue(rule.enabled),
    usage_count: rule.usageCount,
    last_used_at: optionalValue(rule.lastUsedAt),
    created_at: rule.createdAt,
    updated_at: rule.updatedAt,
  }),
  fromRow: row => ({
    id: requiredString(row, 'id'),
    ruleType: requiredString(row, 'rule_type') as UserRule['ruleType'],
    origin: requiredString(row, 'origin') as UserRule['origin'],
    pattern: requiredString(row, 'pattern'),
    transactionType: optionalString(
      row,
      'transaction_type',
    ) as UserRule['transactionType'],
    categoryId: optionalString(row, 'category_id'),
    subcategoryId: optionalString(row, 'subcategory_id'),
    accountId: optionalString(row, 'account_id'),
    priority: requiredNumber(row, 'priority'),
    enabled: requiredBoolean(row, 'enabled'),
    usageCount: requiredNumber(row, 'usage_count'),
    lastUsedAt: optionalString(row, 'last_used_at'),
    createdAt: requiredString(row, 'created_at'),
    updatedAt: requiredString(row, 'updated_at'),
  }),
};

export const classificationFeedbackDefinition: EntityDefinition<ClassificationFeedback> =
  {
    tableName: 'classification_feedback',
    columns: [
      'id',
      'transaction_id',
      'original_type',
      'corrected_type',
      'original_category_id',
      'corrected_category_id',
      'original_subcategory_id',
      'corrected_subcategory_id',
      'original_account_id',
      'corrected_account_id',
      'source_text',
      'merchant_raw_name',
      'learning_status',
      'promoted_rule_id',
      'processed_at',
      'created_at',
    ],
    defaultOrderBy: 'created_at DESC',
    toValues: feedback => ({
      id: feedback.id,
      transaction_id: feedback.transactionId,
      original_type: optionalValue(feedback.originalType),
      corrected_type: optionalValue(feedback.correctedType),
      original_category_id: optionalValue(feedback.originalCategoryId),
      corrected_category_id: optionalValue(feedback.correctedCategoryId),
      original_subcategory_id: optionalValue(feedback.originalSubcategoryId),
      corrected_subcategory_id: optionalValue(feedback.correctedSubcategoryId),
      original_account_id: optionalValue(feedback.originalAccountId),
      corrected_account_id: optionalValue(feedback.correctedAccountId),
      source_text: optionalValue(feedback.sourceText),
      merchant_raw_name: optionalValue(feedback.merchantRawName),
      learning_status: feedback.learningStatus ?? 'PENDING',
      promoted_rule_id: optionalValue(feedback.promotedRuleId),
      processed_at: optionalValue(feedback.processedAt),
      created_at: feedback.createdAt,
    }),
    fromRow: row => ({
      id: requiredString(row, 'id'),
      transactionId: requiredString(row, 'transaction_id'),
      originalType: optionalString(
        row,
        'original_type',
      ) as ClassificationFeedback['originalType'],
      correctedType: optionalString(
        row,
        'corrected_type',
      ) as ClassificationFeedback['correctedType'],
      originalCategoryId: optionalString(row, 'original_category_id'),
      correctedCategoryId: optionalString(row, 'corrected_category_id'),
      originalSubcategoryId: optionalString(row, 'original_subcategory_id'),
      correctedSubcategoryId: optionalString(row, 'corrected_subcategory_id'),
      originalAccountId: optionalString(row, 'original_account_id'),
      correctedAccountId: optionalString(row, 'corrected_account_id'),
      sourceText: optionalString(row, 'source_text'),
      merchantRawName: optionalString(row, 'merchant_raw_name'),
      learningStatus: requiredString(
        row,
        'learning_status',
      ) as ClassificationFeedback['learningStatus'],
      promotedRuleId: optionalString(row, 'promoted_rule_id'),
      processedAt: optionalString(row, 'processed_at'),
      createdAt: requiredString(row, 'created_at'),
    }),
  };

export const budgetDefinition: EntityDefinition<Budget> = {
  tableName: 'budgets',
  columns: [
    'id',
    'period_type',
    'year',
    'month',
    'category_id',
    'limit_minor',
    'currency',
    'created_at',
    'updated_at',
  ],
  defaultOrderBy: 'year DESC, month DESC, category_id ASC',
  toValues: budget => ({
    id: budget.id,
    period_type: budget.periodType,
    year: budget.year,
    month: budget.month,
    category_id: optionalValue(budget.categoryId),
    limit_minor: budget.limitMinor,
    currency: budget.currency,
    created_at: budget.createdAt,
    updated_at: budget.updatedAt,
  }),
  fromRow: row => ({
    id: requiredString(row, 'id'),
    periodType: requiredString(row, 'period_type') as Budget['periodType'],
    year: requiredNumber(row, 'year'),
    month: requiredNumber(row, 'month'),
    categoryId: optionalString(row, 'category_id'),
    limitMinor: requiredNumber(row, 'limit_minor'),
    currency: requiredString(row, 'currency'),
    createdAt: requiredString(row, 'created_at'),
    updatedAt: requiredString(row, 'updated_at'),
  }),
};

export const importRecordDefinition: EntityDefinition<ImportRecord> = {
  tableName: 'import_records',
  columns: [
    'id',
    'source',
    'file_name',
    'source_reference_id',
    'raw_content_hash',
    'parsed_count',
    'imported_count',
    'duplicate_count',
    'failed_count',
    'created_at',
  ],
  defaultOrderBy: 'created_at DESC',
  toValues: record => ({
    id: record.id,
    source: record.source,
    file_name: optionalValue(record.fileName),
    source_reference_id: optionalValue(record.sourceReferenceId),
    raw_content_hash: optionalValue(record.rawContentHash),
    parsed_count: record.parsedCount,
    imported_count: record.importedCount,
    duplicate_count: record.duplicateCount,
    failed_count: record.failedCount,
    created_at: record.createdAt,
  }),
  fromRow: row => ({
    id: requiredString(row, 'id'),
    source: requiredString(row, 'source') as ImportRecord['source'],
    fileName: optionalString(row, 'file_name'),
    sourceReferenceId: optionalString(row, 'source_reference_id'),
    rawContentHash: optionalString(row, 'raw_content_hash'),
    parsedCount: requiredNumber(row, 'parsed_count'),
    importedCount: requiredNumber(row, 'imported_count'),
    duplicateCount: requiredNumber(row, 'duplicate_count'),
    failedCount: requiredNumber(row, 'failed_count'),
    createdAt: requiredString(row, 'created_at'),
  }),
};
